from collections import namedtuple

CocoClass = namedtuple('CocoClass', 'id name')
CocoClass.__doc__ = 'Common Objects in Context class'
CocoClass.id.__doc__ = 'Class ID'
CocoClass.name.__doc__ = 'Human readable name or label' 

coco_classes_by_id = [
    CocoClass(0, "unlabeled"),
    CocoClass(1, "person"),
    CocoClass(2, "bicycle"),
    CocoClass(3, "car"),
    CocoClass(4, "motorcycle"),
    CocoClass(5, "airplane"),
    CocoClass(6, "bus"),
    CocoClass(7, "train"),
    CocoClass(8, "truck"),
    CocoClass(9, "boat"),
    CocoClass(10, "traffic light"),
    CocoClass(11, "fire hydrant"),
    CocoClass(12, "street sign"),
    CocoClass(13, "stop sign"),
    CocoClass(14, "parking meter"),
    CocoClass(15, "bench"),
    CocoClass(16, "bird"),
    CocoClass(17, "cat"),
    CocoClass(18, "dog"),
    CocoClass(19, "horse"),
    CocoClass(20, "sheep"),
    CocoClass(21, "cow"),
    CocoClass(22, "elephant"),
    CocoClass(23, "bear"),
    CocoClass(24, "zebra"),
    CocoClass(25, "giraffe"),
    CocoClass(26, "hat"),
    CocoClass(27, "backpack"),
    CocoClass(28, "umbrella"),
    CocoClass(29, "shoe"),
    CocoClass(30, "eye glasses"),
    CocoClass(31, "handbag"),
    CocoClass(32, "tie"),
    CocoClass(33, "suitcase"),
    CocoClass(34, "frisbee"),
    CocoClass(35, "skis"),
    CocoClass(36, "snowboard"),
    CocoClass(37, "sports ball"),
    CocoClass(38, "kite"),
    CocoClass(39, "baseball bat"),
    CocoClass(40, "baseball glove"),
    CocoClass(41, "skateboard"),
    CocoClass(42, "surfboard"),
    CocoClass(43, "tennis racket"),
    CocoClass(44, "bottle"),
    CocoClass(45, "plate"),
    CocoClass(46, "wine glass"),
    CocoClass(47, "cup"),
    CocoClass(48, "fork"),
    CocoClass(49, "knife"),
    CocoClass(50, "spoon"),
    CocoClass(51, "bowl"),
    CocoClass(52, "banana"),
    CocoClass(53, "apple"),
    CocoClass(54, "sandwich"),
    CocoClass(55, "orange"),
    CocoClass(56, "broccoli"),
    CocoClass(57, "carrot"),
    CocoClass(58, "hot dog"),
    CocoClass(59, "pizza"),
    CocoClass(60, "donut"),
    CocoClass(61, "cake"),
    CocoClass(62, "chair"),
    CocoClass(63, "couch"),
    CocoClass(64, "potted plant"),
    CocoClass(65, "bed"),
    CocoClass(66, "mirror"),
    CocoClass(67, "dining table"),
    CocoClass(68, "window"),
    CocoClass(69, "desk"),
    CocoClass(70, "toilet"),
    CocoClass(71, "door"),
    CocoClass(72, "tv"),
    CocoClass(73, "laptop"),
    CocoClass(74, "mouse"),
    CocoClass(75, "remote"),
    CocoClass(76, "keyboard"),
    CocoClass(77, "cell phone"),
    CocoClass(78, "microwave"),
    CocoClass(79, "oven"),
    CocoClass(80, "toaster"),
    CocoClass(81, "sink"),
    CocoClass(82, "refrigerator"),
    CocoClass(83, "blender"),
    CocoClass(84, "book"),
    CocoClass(85, "clock"),
    CocoClass(86, "vase"),
    CocoClass(87, "scissors"),
    CocoClass(88, "teddy bear"),
    CocoClass(89, "hair drier"),
    CocoClass(90, "toothbrush")
]


coco_classes_by_name = {
    "unlabeled": coco_classes_by_id[0],
    "person": coco_classes_by_id[1],
    "bicycle": coco_classes_by_id[2],
    "car": coco_classes_by_id[3],
    "motorcycle": coco_classes_by_id[4],
    "airplane": coco_classes_by_id[5],
    "bus": coco_classes_by_id[6],
    "train": coco_classes_by_id[7],
    "truck": coco_classes_by_id[8],
    "boat": coco_classes_by_id[9],
    "traffic light": coco_classes_by_id[10],
    "fire hydrant": coco_classes_by_id[11],
    "street sign": coco_classes_by_id[12],
    "stop sign": coco_classes_by_id[13],
    "parking meter": coco_classes_by_id[14],
    "bench": coco_classes_by_id[15],
    "bird": coco_classes_by_id[16],
    "cat": coco_classes_by_id[17],
    "dog": coco_classes_by_id[18],
    "horse": coco_classes_by_id[19],
    "sheep": coco_classes_by_id[20],
    "cow": coco_classes_by_id[21],
    "elephant": coco_classes_by_id[22],
    "bear": coco_classes_by_id[23],
    "zebra": coco_classes_by_id[24],
    "giraffe": coco_classes_by_id[25],
    "hat": coco_classes_by_id[26],
    "backpack": coco_classes_by_id[27],
    "umbrella": coco_classes_by_id[28],
    "shoe": coco_classes_by_id[29],
    "eye glasses": coco_classes_by_id[30],
    "handbag": coco_classes_by_id[31],
    "tie": coco_classes_by_id[32],
    "suitcase": coco_classes_by_id[33],
    "frisbee": coco_classes_by_id[34],
    "skis": coco_classes_by_id[35],
    "snowboard": coco_classes_by_id[36],
    "sports ball": coco_classes_by_id[37],
    "kite": coco_classes_by_id[38],
    "baseball bat": coco_classes_by_id[39],
    "baseball glove": coco_classes_by_id[40],
    "skateboard": coco_classes_by_id[41],
    "surfboard": coco_classes_by_id[42],
    "tennis racket": coco_classes_by_id[43],
    "bottle": coco_classes_by_id[44],
    "plate": coco_classes_by_id[45],
    "wine glass": coco_classes_by_id[46],
    "cup": coco_classes_by_id[47],
    "fork": coco_classes_by_id[48],
    "knife": coco_classes_by_id[49],
    "spoon": coco_classes_by_id[50],
    "bowl": coco_classes_by_id[51],
    "banana": coco_classes_by_id[52],
    "apple": coco_classes_by_id[53],
    "sandwich": coco_classes_by_id[54],
    "orange": coco_classes_by_id[55],
    "broccoli": coco_classes_by_id[56],
    "carrot": coco_classes_by_id[57],
    "hot dog": coco_classes_by_id[58],
    "pizza": coco_classes_by_id[59],
    "donut": coco_classes_by_id[60],
    "cake": coco_classes_by_id[61],
    "chair": coco_classes_by_id[62],
    "couch": coco_classes_by_id[63],
    "potted plant": coco_classes_by_id[64],
    "bed": coco_classes_by_id[65],
    "mirror": coco_classes_by_id[66],
    "dining table": coco_classes_by_id[67],
    "window": coco_classes_by_id[68],
    "desk": coco_classes_by_id[69],
    "toilet": coco_classes_by_id[70],
    "door": coco_classes_by_id[71],
    "tv": coco_classes_by_id[72],
    "laptop": coco_classes_by_id[73],
    "mouse": coco_classes_by_id[74],
    "remote": coco_classes_by_id[75],
    "keyboard": coco_classes_by_id[76],
    "cell phone": coco_classes_by_id[77],
    "microwave": coco_classes_by_id[78],
    "oven": coco_classes_by_id[79],
    "toaster": coco_classes_by_id[80],
    "sink": coco_classes_by_id[81],
    "refrigerator": coco_classes_by_id[82],
    "blender": coco_classes_by_id[83],
    "book": coco_classes_by_id[84],
    "clock": coco_classes_by_id[85],
    "vase": coco_classes_by_id[86],
    "scissors": coco_classes_by_id[87],
    "teddy bear": coco_classes_by_id[88],
    "hair drier": coco_classes_by_id[89],
    "toothbrush": coco_classes_by_id[90]
}
