from collections import namedtuple

CocoClass = namedtuple('CocoClass', 'id label')

coco_classes_by_id = [
    CocoClass(0, "unlabeled"),
    CocoClass(1, "person"),
    CocoClass(2, "bicycle"),
    CocoClass(3, "car"),
    CocoClass(4, "motorcycle"),
    CocoClass(5, "airplane"),
    CocoClass(6, "bus"),
    CocoClass(7, "train"),
    CocoClass(8, "truck"),
    CocoClass(9, "boat"),
    CocoClass(10, "traffic light"),
    CocoClass(11, "fire hydrant"),
    CocoClass(12, "street sign"),
    CocoClass(13, "stop sign"),
    CocoClass(14, "parking meter"),
    CocoClass(15, "bench"),
    CocoClass(16, "bird"),
    CocoClass(17, "cat"),
    CocoClass(18, "dog"),
    CocoClass(19, "horse"),
    CocoClass(20, "sheep"),
    CocoClass(21, "cow"),
    CocoClass(22, "elephant"),
    CocoClass(23, "bear"),
    CocoClass(24, "zebra"),
    CocoClass(25, "giraffe"),
    CocoClass(26, "hat"),
    CocoClass(27, "backpack"),
    CocoClass(28, "umbrella"),
    CocoClass(29, "shoe"),
    CocoClass(30, "eye glasses"),
    CocoClass(31, "handbag"),
    CocoClass(32, "tie"),
    CocoClass(33, "suitcase"),
    CocoClass(34, "frisbee"),
    CocoClass(35, "skis"),
    CocoClass(36, "snowboard"),
    CocoClass(37, "sports ball"),
    CocoClass(38, "kite"),
    CocoClass(39, "baseball bat"),
    CocoClass(40, "baseball glove"),
    CocoClass(41, "skateboard"),
    CocoClass(42, "surfboard"),
    CocoClass(43, "tennis racket"),
    CocoClass(44, "bottle"),
    CocoClass(45, "plate"),
    CocoClass(46, "wine glass"),
    CocoClass(47, "cup"),
    CocoClass(48, "fork"),
    CocoClass(49, "knife"),
    CocoClass(50, "spoon"),
    CocoClass(51, "bowl"),
    CocoClass(52, "banana"),
    CocoClass(53, "apple"),
    CocoClass(54, "sandwich"),
    CocoClass(55, "orange"),
    CocoClass(56, "broccoli"),
    CocoClass(57, "carrot"),
    CocoClass(58, "hot dog"),
    CocoClass(59, "pizza"),
    CocoClass(60, "donut"),
    CocoClass(61, "cake"),
    CocoClass(62, "chair"),
    CocoClass(63, "couch"),
    CocoClass(64, "potted plant"),
    CocoClass(65, "bed"),
    CocoClass(66, "mirror"),
    CocoClass(67, "dining table"),
    CocoClass(68, "window"),
    CocoClass(69, "desk"),
    CocoClass(70, "toilet"),
    CocoClass(71, "door"),
    CocoClass(72, "tv"),
    CocoClass(73, "laptop"),
    CocoClass(74, "mouse"),
    CocoClass(75, "remote"),
    CocoClass(76, "keyboard"),
    CocoClass(77, "cell phone"),
    CocoClass(78, "microwave"),
    CocoClass(79, "oven"),
    CocoClass(80, "toaster"),
    CocoClass(81, "sink"),
    CocoClass(82, "refrigerator"),
    CocoClass(83, "blender"),
    CocoClass(84, "book"),
    CocoClass(85, "clock"),
    CocoClass(86, "vase"),
    CocoClass(87, "scissors"),
    CocoClass(88, "teddy bear"),
    CocoClass(89, "hair drier"),
    CocoClass(90, "toothbrush")
]
